# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
pt:
 languageCode: pt
 contentDir: content/pt
 title: Thaís Paiva
 # params:
 #   description: Site description in Chinese...
 # menu:
 #   main:
 #     - name: Thaís
 #       url: '#about'
 #       weight: 1
