---
# An instance of the Pages widget.
# Documentation: https://wowchemy.com/docs/page-builder/
widget: markdown
# type: landing

# This file represents a page section.
headless: true

# Order that this section appears on the page.
weight: 30

title: Teaching
subtitle: UFMG
date: FALSE

---

### <span style="color:red">2023/1:</span>
- [EST053 - Computational Methods for Risk Analysis](http://www.est.ufmg.br/~thaispaiva/MetComp/)
- EST049 - Actuarial Mathematics II
- EST072 - Economic Statistics I

### 2022:
- EST047 - Actuarial Mathematics I
- EST049 - Actuarial Mathematics II
- EST053 - Computational Methods for Risk Analysis
- EST053 - Actuary Topics: IBA Exam Preparation 
&nbsp;  

- EST057 - Intro to Statistics
- EST179 - Intro to Biostatistics

### 2021:
- EST051 - Actuarial Practices
- EST052 - Insurance Tariffing
- EST053 - Actuary Topics: IBA Exam Preparation 
- EST188 - Statistical Lab I

- EST179 - Intro to Biostatistics
- EST083 - Basic Biostatistics
- EST084 - Statistics applied to Psychology

### 2020:
- EST051 - Actuarial Practices
- EST053 - Computational Methods for Risk Analysis
- EST179 - Intro to Biostatistics
- EST188 - Statistical Lab I

### 2016 a 2019:
- EST047 - Actuarial Mathematics I
- EST049 - Actuarial Mathematics II
- EST051 - Actuarial Practices
- EST052 - Insurance Tariffing
- EST171 - Computational Methods for Risk Analysis

- EST031 - Statistics and Probability
- EST084 - Statistics applied to Psychology
- EST179 - Intro to Biostatistics